doctrine:
    dbal:
        # configure these for your database server
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            common:
                url: '%env(resolve:COMMON_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            reseller:
                url: '%env(resolve:RESELLER_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: default
                mappings:
                    # App:
                    #     is_bundle: false
                    #     type: attribute
                    #     dir: '%kernel.project_dir%/src/Entity'
                    #     prefix: 'App\Entity'
                    #     alias: App
                    Common:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Common'
                        prefix: 'App\Entity\Common'
                    Reseller:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Reseller'
                        prefix: 'App\Entity\Reseller'
                    Returns:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Returns'
                        prefix: 'App\Entity\Returns'
            common:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: common
                mappings:
                    Common:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Common'
                        prefix: 'App\Entity\Common'
            reseller:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: reseller
                mappings:
                    Reseller:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Reseller'
                        prefix: 'App\Entity\Reseller'